apiVersion: apps/v1
kind: Deployment
metadata:
  name: zaks-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zaks-site
  template:
    metadata:
      labels:
        app: zaks-site
    spec:
      volumes:
        - name: web-content
          emptyDir: {}

      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-content
              mountPath: /usr/share/nginx/html

        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v4.0.0
          env:
            - name: GITSYNC_REPO
              value: "https://github.com/zakcole08/zakcole08.github.io"
            - name: GITSYNC_BRANCH
              value: "main"
            - name: GITSYNC_ROOT
              value: "/git"
            - name: GITSYNC_DEST
              value: "."
            - name: GITSYNC_WAIT
              value: "30"
            - name: GITSYNC_ONE_TIME
              value: "false"
          volumeMounts:
            - name: web-content
              mountPath: /usr/share/nginx/html
